#!/bin/bash

kubectl delete secret dmm-certs
kubectl delete secret dmm-config

kubectl create secret generic dmm-certs --from-file=$HOME/private/certs/rucio-sense/cert.pem --from-file=$HOME/private/certs/rucio-sense/key.pem
kubectl create secret generic dmm-config --from-file=$HOME/private/dmm.cfg
